name: Node.js CI

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

env:
    AZURE_WEBAPP_NAME: drai-auth
    AZURE_WEBAPP_PACKAGE_PATH: '.'
    NODE_VERSION: '14.x'

jobs:
    sonarcloud:
        name: SonarCloud
        runs-on: ubuntu-latest
        environment: test
        steps:
            -   uses: actions/checkout@v2
                with:
                    fetch-depth: 0

            -   uses: actions/setup-node@v2
                with:
                    node-version: ${{ env.NODE_VERSION }}
                    cache: 'npm'

            -   name: Install dependencies
                run: npm install

            -   name: Build
                run: npm run build --if-present

            -   name: run Tests
                run: npm run test:ci

            -   name: SonarCloud Scan
                uses: SonarSource/sonarcloud-github-action@master
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    deploy:
        needs: sonarcloud
        environment: prod
        name: Build and Deploy
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -   name: Use Node.js ${{ env.NODE_VERSION }}
                uses: actions/setup-node@v2
                with:
                    node-version: ${{ env.NODE_VERSION }}

            -   name: Install dependencies
                run: npm install

            -   name: Build
                run: npm run build --if-present

            -   name: 'Deploy to Azure WebApp'
                uses: azure/webapps-deploy@0b651ed7546ecfc75024011f76944cb9b381ef1e
                with:
                    app-name: ${{ env.AZURE_WEBAPP_NAME }}
                    publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
                    package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
