name: Node.js CI

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

env:
    NODE_VERSION: '14.x'

jobs:
    sonarcloud:
        name: SonarCloud
        runs-on: ubuntu-latest
        environment: test
        steps:
            -   uses: actions/checkout@v2
                with:
                    fetch-depth: 0

            -   uses: actions/setup-node@v2
                with:
                    node-version: ${{ env.NODE_VERSION }}
                    cache: 'yarn'

            -   name: Install dependencies
                run: yarn install

            -   name: Build
                run: yarn build --if-present

            -   name: run Tests
                run: yarn test:ci

            -   name: SonarCloud Scan
                uses: SonarSource/sonarcloud-github-action@master
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    deploy:
        needs: sonarcloud
        environment: prod
        name: Build and Deploy
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -   name: Use Node.js ${{ env.NODE_VERSION }}
                uses: actions/setup-node@v2
                with:
                    node-version: ${{ env.NODE_VERSION }}

            -   name: 'Deploy to Vercel'
                run: yarn deploy
